/**
 * The in-headset UI's look: the 2D panels' design tokens, carried into VR.
 *
 * The values mirror the custom properties at the top of src/ui/styles.css, so
 * the headset panels read as the same instrument as the page. Two departures,
 * both for legibility through a headset's lenses: the panel is more opaque
 * than on the page (0.88 against 0.72), since a starfield shimmering through
 * text is harder to read in stereo than on a monitor, and the faintest text
 * uses the brighter grey the accessibility review asked for.
 *
 * uikit 1.0 takes opacity inside the colour, so everything translucent is
 * written as #rrggbbaa.
 */

import type { FontFamilies } from '@pmndrs/uikit';
import { INTER_REGULAR } from '../../data/generated/fonts/inter-regular.ts';
import { INTER_SEMIBOLD } from '../../data/generated/fonts/inter-semibold.ts';
import { JETBRAINS_MONO_REGULAR } from '../../data/generated/fonts/jetbrains-mono-regular.ts';

export const COLOR = {
  /** --panel, at 0.88 */
  panel: '#0a0e16e0',
  /** A raised surface inside the panel: rows and idle buttons. */
  surface: '#ffffff0e',
  surfaceHover: '#ffffff1a',
  /** --border */
  border: '#96b4dc24',
  /** --border-strong */
  borderStrong: '#96b4dc47',
  /** --text */
  text: '#dce4f0',
  /** --text-dim */
  textDim: '#8794a8',
  /** --text-faint, brightened to about 4.5:1 on the panel */
  textFaint: '#7b8799',
  /** --accent */
  accent: '#6fb3ff',
  /** --accent-dim */
  accentDim: '#6fb3ff26',
  /** --warn */
  warn: '#ffb35c',
} as const;

/**
 * The fonts, generated by `pnpm assets:fonts` with the glyphs Aphelion
 * actually prints. `mono` is for readouts that change while you watch: every
 * digit has the same advance, so a ticking clock neither jitters nor reflows.
 */
export const FONT_FAMILIES: FontFamilies = {
  inter: { normal: INTER_REGULAR, 'semi-bold': INTER_SEMIBOLD },
  mono: { normal: JETBRAINS_MONO_REGULAR },
};

/**
 * Metres per layout pixel. The panel is laid out in pixels like the page and
 * scaled into the room by this: 14 px body text is then 10.5 mm tall, about
 * three quarters of a degree at arm's length — the size a phone's text is
 * held at.
 */
export const PIXEL_SIZE = 0.00075;

/** The panel's layout size, in pixels. */
export const PANEL_WIDTH = 480;
export const PANEL_HEIGHT = 420;

export const RADIUS = 14;

/** Section titles: small, letter-spaced capitals, like `.panel__title` on the page. */
export const TITLE = {
  fontSize: 11,
  fontWeight: 'semi-bold',
  letterSpacing: 1.5,
  color: COLOR.textFaint,
} as const;

/**
 * A scrolling area, with the thumb drawn thin in the border colour like the
 * page's scrollbars; uikit's default is a solid white bar.
 */
export const SCROLL = {
  flexGrow: 1,
  minHeight: 0,
  overflow: 'scroll',
  paddingRight: 8,
  scrollbarWidth: 3,
  scrollbarColor: COLOR.borderStrong,
  scrollbarBorderTopLeftRadius: 2,
  scrollbarBorderTopRightRadius: 2,
  scrollbarBorderBottomLeftRadius: 2,
  scrollbarBorderBottomRightRadius: 2,
} as const;
