/** The texture manifest: which textures actually made it onto disk. */

import fs from 'node:fs/promises';
import path from 'node:path';
import { C, GENERATED, TEXTURES } from './io.ts';

/** Lets the app know which textures actually made it onto disk. */
export async function writeManifest(): Promise<void> {
  let names: string[] = [];
  try {
    names = (await fs.readdir(TEXTURES)).filter((f) => /\.(jpg|png|webp)$/iu.test(f)).toSorted();
  } catch {
    names = [];
  }
  const src = `/**
 * GENERATED by scripts/fetch-assets.ts -- do not edit by hand.
 *
 * Textures present in public/textures. Anything absent falls back to the
 * procedural generator in src/render/procedural/, which is why the app still
 * runs -- and still looks right -- before \`pnpm assets\` has been run.
 */

export const AVAILABLE_TEXTURES: ReadonlySet<string> = new Set(${JSON.stringify(names, null, 2)})

export const hasTexture = (file: string): boolean => AVAILABLE_TEXTURES.has(file)
`;
  await fs.mkdir(GENERATED, { recursive: true });
  await fs.writeFile(path.join(GENERATED, 'textures.ts'), src);
  console.log(
    `  ${C.green('wrote  ')} src/data/generated/textures.ts ${C.dim(`(${names.length} textures)`)}`,
  );
}
