/** Writing src/data/generated/relief.ts from the relief maps that were built. */

import type { ReliefResult } from './relief.ts';
import fs from 'node:fs/promises';
import path from 'node:path';
import { C, GENERATED } from './io.ts';

export async function writeReliefModule(results: ReliefResult[]): Promise<void> {
  const entries = results
    .map(
      // Keys are quoted because moons are keyed 'moon:Moon', which is not an
      // identifier.
      (r) => `  '${r.body}': {
    file: '${r.out}',
    width: ${r.width},
    height: ${r.height},
    minKm: ${r.minKm.toFixed(4)},
    maxKm: ${r.maxKm.toFixed(4)},
    credit: '${r.credit.replaceAll("'", "\\'")}',
  },`,
    )
    .join('\n');

  const src = `/**
 * GENERATED by scripts/fetch-assets.ts -- do not edit by hand.
 *
 * Global elevation grids present in public/shapes, with the elevation range each
 * one was quantised against. A body with no entry here renders as its reference
 * ellipsoid, which is why the app still works before \`pnpm assets\` has run.
 *
 * Encoding: equirectangular, left edge 180 degrees west (matching the colour
 * mosaics), north row first. Elevation is a 16-bit fraction split across the red
 * (high byte) and green (low byte) channels:
 *
 *   km = minKm + (R * 256 + G) / 65535 * (maxKm - minKm)
 *
 * relative to the body's reference radius.
 */

export interface ReliefMap {
  file: string
  width: number
  height: number
  /** Elevation encoded by 0, km relative to the body's reference radius. */
  minKm: number
  /** Elevation encoded by 65535. */
  maxKm: number
  credit: string
}

export const RELIEF_MAPS: Readonly<Record<string, ReliefMap>> = {
${entries}
}

export const reliefFor = (key: string): ReliefMap | null => RELIEF_MAPS[key] ?? null
`;
  await fs.mkdir(GENERATED, { recursive: true });
  await fs.writeFile(path.join(GENERATED, 'relief.ts'), src);
  console.log(
    `  ${C.green('wrote  ')} src/data/generated/relief.ts ${C.dim(`(${results.length} maps)`)}`,
  );
}
