/** Packing the star catalogue into public/sky, with the module that describes it. */

import type { Star } from './stars.ts';
import fs from 'node:fs/promises';
import path from 'node:path';
import { C, GENERATED, mb, SKY } from './io.ts';
import { clampPm, HIPPARCOS_EPOCH, STAR_FILE, STAR_MAG_LIMIT, STAR_MAGIC } from './stars.ts';

/**
 * Write the packed catalogue and the module that describes it.
 *
 * Struct of arrays rather than interleaved records, so each block uploads to
 * the GPU as one buffer attribute with no unpacking pass. The 16-byte header
 * keeps the 2-byte blocks aligned.
 */
export async function writeStarCatalogue(stars: Star[]): Promise<void> {
  const n = stars.length;
  const HEADER = 16;
  const bytes = HEADER + n * 2 + n * 2 + n * 4 + n * 2 + n * 3;
  const buf = Buffer.alloc(bytes);

  buf.writeUInt32LE(STAR_MAGIC, 0);
  buf.writeUInt32LE(1, 4); // format version
  buf.writeUInt32LE(n, 8);
  buf.writeFloatLE(STAR_MAG_LIMIT, 12);

  let o = HEADER;
  const raAt = o;
  o += n * 2;
  const decAt = o;
  o += n * 2;
  const pmAt = o;
  o += n * 4;
  const magAt = o;
  o += n * 2;
  const rgbAt = o;

  const TWO_PI = Math.PI * 2;
  for (let i = 0; i < n; i++) {
    const s = stars[i];
    // RA spans a full turn, so it uses the whole unsigned range; dec spans half
    // a turn about zero, so it uses the signed one. Both quantise to under
    // 20 arcsec, a fifth of a pixel at this field of view.
    buf.writeUInt16LE(
      Math.round(((((s.ra % TWO_PI) + TWO_PI) % TWO_PI) / TWO_PI) * 65536) % 65536,
      raAt + i * 2,
    );
    buf.writeInt16LE(
      Math.max(-32767, Math.min(32767, Math.round((s.dec / (Math.PI / 2)) * 32767))),
      decAt + i * 2,
    );
    buf.writeInt16LE(clampPm(s.pmRA), pmAt + i * 4);
    buf.writeInt16LE(clampPm(s.pmDec), pmAt + i * 4 + 2);
    buf.writeInt16LE(Math.max(-32767, Math.min(32767, Math.round(s.vmag * 1000))), magAt + i * 2);
    buf[rgbAt + i * 3] = s.rgb[0];
    buf[rgbAt + i * 3 + 1] = s.rgb[1];
    buf[rgbAt + i * 3 + 2] = s.rgb[2];
  }

  await fs.mkdir(SKY, { recursive: true });
  await fs.writeFile(path.join(SKY, STAR_FILE), buf);
  console.log(
    `  ${C.green('wrote  ')} public/sky/${STAR_FILE} ${C.dim(`(${n} stars, ${mb(bytes)})`)}`,
  );

  const brightest = stars.toSorted((a, b) => a.vmag - b.vmag)[0];
  const src = `/**
 * GENERATED by scripts/fetch-assets.ts -- do not edit by hand.
 *
 * Describes public/sky/${STAR_FILE}, the packed Hipparcos catalogue the sky
 * draws as point sources. The binary carries the same count and magnitude limit
 * in its header; the loader compares the two so a stale file is refused rather
 * than rendered as a wrong sky.
 *
 * Positions are ICRF/J2000 right ascension and declination, propagated from the
 * catalogue epoch J${HIPPARCOS_EPOCH} with each star's own proper motion. They are NOT
 * precessed to date at runtime and must not be: Aphelion's frame is inertial
 * (ecliptic J2000), so precession moves the coordinate grid, not the stars.
 *
 * Layout, little-endian, after a 16-byte header of
 * [magic u32, version u32, count u32, magnitudeLimit f32]:
 *
 *   Uint16Array[count]      right ascension, full turn over the u16 range
 *   Int16Array[count]       declination, +-90 deg over the i16 range
 *   Int16Array[count * 2]   proper motion (RA*cos dec, dec), mas/yr
 *   Int16Array[count]       Johnson V magnitude, millimagnitudes
 *   Uint8Array[count * 3]   sRGB chromaticity from the B-V colour index
 */

export const STAR_CATALOGUE = {
  /** Path under public/, loaded at runtime like a texture. */
  file: 'sky/${STAR_FILE}',
  count: ${n},
  /** Faintest V magnitude present. */
  magnitudeLimit: ${STAR_MAG_LIMIT},
  /** Epoch the positions were propagated to, as a Julian year. */
  epoch: 2000.0,
  /** Byte offset of the first array; the header occupies everything before it. */
  headerBytes: ${HEADER},
  magic: ${STAR_MAGIC},
  version: 1,
} as const
`;
  await fs.mkdir(GENERATED, { recursive: true });
  await fs.writeFile(path.join(GENERATED, 'stars.ts'), src);
  console.log(
    `  ${C.green('wrote  ')} src/data/generated/stars.ts ${C.dim(`(brightest V ${brightest.vmag.toFixed(2)})`)}`,
  );
}
